apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: app-is-bc
message: S2I docker builder
metadata:
  name: "${IS_NAME}"
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "${IS_NAME}"
  spec:
    runPolicy: "Serial"
    source:
      git:
        uri: "${GIT_REPO}"
        ref: "${GIT_REF}"
    strategy:
      sourceStrategy:
        from:
          kind: "ImageStreamTag"
          name: "java:latest"
          namespace: openshift
    output:
      to:
        kind: "DockerImage"
        name: "${REGISTRY_NAME}/${IMAGE_NAME}:${IMAGE_TAG}"
      pushSecret:
        name: ${PUSH_SECRET}
parameters:
- name: IS_NAME
  required: true
  value: kbit-api-s2i
- name: REGISTRY_NAME
  required: true
  value: "docker.io/dimssss"
- name: IMAGE_NAME
  required: true
  value: "kbit-api"
- name: IMAGE_TAG
  required: true
  value: latest
- name: GIT_REPO
  required: true
  value: "https://github.com/Dimss/kbit-api"
- name: GIT_REF
  required: true
  value: "master"
- name: PUSH_SECRET
  required: true
  value: "dimssss-docker-io"

