kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "kbit-api"
spec:
  source:
    git:
      uri: "https://github.com/Dimss/kbit-api"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile:
      env:
      - name: "VERSION"
        value: ""
    type: JenkinsPipeline
  triggers:
  - generic:
      allowEnv: true
      secret: trigger-secret
    type: Generic