kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "kbit-api"
spec:
  source:
    git:
      uri: "https://github.com/Dimss/kbit-api"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile:
      env:
      - name: "NAME"
        value: "kbit-api"
      - name: "VERSION"
        value: ""
      - name: "IMAGE_NAME"
        value: "kbit-api"
    type: JenkinsPipeline
  triggers:
  - generic:
      allowEnv: true
      secret: trigger-secret
    type: Generic