kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "kbit-api"
spec:
  source:
    git:
      uri: "https://github.com/Dimss/kbit-api"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile:
      env:
      - name: "NAME"
        value: "kbit-api"
      - name: "REGISTRY_NAME"
        value: "docker.io/dimssss"
      - name: "IMAGE_NAME"
        value: "kbit-api"
    type: JenkinsPipeline
